import { StyleSheet } from "react-native";
import { colors } from "../colors";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: colors.champagne,
  },
  searchInput: {
    backgroundColor: colors.sunset,
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchInputText: {
    fontSize: 16,
    color: colors.sealbrown,
    flex: 1,
    marginRight: 8,
  },
  emptyStateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 100,
  },
  emptyStateImage: {
    width: 200,
    height: 200,
    marginBottom: 16,
  },
  emptyStateText: {
    fontSize: 16,
    color: colors.sealbrown,
    textAlign: 'center',
    marginTop: 8,
  },
  currentWeather: {
    backgroundColor: colors.sunset,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  loadingIndicator: {
    alignSelf: 'center',
  },
  currentWeatherHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  weatherIcon: {
    width: 100,
    height: 100,
    alignSelf: 'center',
  },
  temperature: {
    fontSize: 48,
    textAlign: 'center',
    color: colors.sealbrown,
  },
  weatherDescription: {
    fontSize: 18,
    textAlign: 'center',
    color: colors.sealbrown,
    marginBottom: 10,
  },
  weatherDetail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  weatherDetailText: {
    fontSize: 16,
    color: colors.sealbrown,
  },
  forecastContainer: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  forecastCard: {
    backgroundColor: colors.sunset,
    borderRadius: 8,
    padding: 10,
    marginRight: 10,
    width: 120,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  forecastDate: {
    fontSize: 16,
    color: colors.sealbrown,
  },
  forecastIcon: {
    width: 50,
    height: 50,
    alignSelf: 'center',
  },
  forecastTemp: {
    fontSize: 16,
    textAlign: 'center',
    color: colors.sealbrown,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: colors.sealbrown,
  },
  recentSearchItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  recentSearchText: {
    fontSize: 16,
    color: colors.sealbrown,
  },
  refreshButton: {
    marginTop: 20,
    padding: 15,
    borderRadius: 8,
  },
  refreshButtonText: {
    fontSize: 16,
    color: colors.sealbrown,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
});